package com.tompy.directive;

public enum EventType {
    EVENT_AREA_SEARCH, EVENT_AREA_NORTH_SEARCH, EVENT_AREA_EAST_SEARCH, EVENT_AREA_SOUTH_SEARCH, EVENT_AREA_WEST_SEARCH,
    EVENT_AREA_ENTER, EVENT_AREA_ENTER_NORTH, EVENT_AREA_ENTER_EAST, EVENT_AREA_ENTER_SOUTH, EVENT_AREA_ENTER_WEST,
    EVENT_AREA_EXIT, EVENT_AREA_EXIT_NORTH, EVENT_AREA_EXIT_EAST, EVENT_AREA_EXIT_SOUTH, EVENT_AREA_EXIT_WEST,
    EVENT_INTERACTION, EVENT_FEATURE_SEARCH, EVENT_FEATURE_OPEN, EVENT_FEATURE_CLOSE, EVENT_FEATURE_LOCK,
    EVENT_FEATURE_UNLOCK, EVENT_FEATURE_DRINK, EVENT_FEATURE_TRAP, EVENT_START_ROUND, EVENT_EXPLORING,
    EVENT_ATTACK_SUCCESS, EVENT_ATTACK_FAILURE;
}
