package com.tompy.directive;

public enum EventType {
    AREA_SEARCH, AREA_NORTH_SEARCH, AREA_EAST_SEARCH, AREA_SOUTH_SEARCH, AREA_WEST_SEARCH, AREA_ENTER,
    AREA_ENTER_NORTH, AREA_ENTER_EAST, AREA_ENTER_SOUTH, AREA_ENTER_WEST, AREA_EXIT, AREA_EXIT_NORTH, AREA_EXIT_EAST,
    AREA_EXIT_SOUTH, AREA_EXIT_WEST, INTERACTION, FEATURE_SEARCH, FEATURE_OPEN, FEATURE_CLOSE, FEATURE_LOCK, FEATURE_UNLOCK,
    FEATURE_DRINK, FEATURE_TRAP, START_ROUND, EXPLORING;
}
